import express from "express";
// import { Router } from "express";
import signUpController from "../Controllers/signUpController.js";
import loginController from "../Controllers/loginController.js";
import sendOtpController from "../Controllers/sendOtpController.js";
import { verifyOtpController } from "../Controllers/verifyOtpController.js";
const loginRoutes=express.Router();
loginRoutes.post("/signup",signUpController);
loginRoutes.post("/login",loginController);
loginRoutes.post("/send-otp",sendOtpController);
loginRoutes.post("/verifyotp",verifyOtpController);
export default loginRoutes;